import React from "react";
import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Tokomi Store",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <CartProvider>
        {children}
        </CartProvider>
        </body>
        </html>
    );
}
